"""Fraud detection — layers 1 and 2, entity resolution, document checks, routing.

Phase 1 WS-1.2 (SRS §5). Track A reference implementations behind the interfaces
the Track B stack (splink, Flink, LightGBM, scikit-learn, docTR) plugs into —
see ADR-0003 and ADR-0011.

Workstream: WS-1.2
"""

from .entity_resolution import (
    GEOHASH_PRECISION,
    MATCH_THRESHOLD,
    ApplicationRecord,
    Edge,
    EdgeType,
    EntityGraph,
    EntityResolutionError,
    MatchScore,
    Node,
    NodeType,
    build_graph,
    candidate_pairs,
    compare,
    geohash,
    jaro,
    jaro_winkler,
    normalise_account,
    normalise_name,
    normalise_phone,
    resolve,
)

from .anomaly import (
    ANOMALY_FEATURE,
    DEFAULT_MAX_SAMPLES,
    DEFAULT_N_ESTIMATORS,
    AnomalyError,
    IsolationForest,
    anomaly_feature,
    average_path_length,
    fit_isolation_forest,
)
from .supervised import (
    ALERT_BUDGET,
    EVALUATION_ALERT_RATE,
    MAX_STEP_UP_FRICTION,
    MINIMUM_CONFIRMED_FRAUDS,
    FraudEvaluation,
    FraudLabels,
    FraudModel,
    FraudModelError,
    Scope,
    average_precision,
    evaluate,
    fit_fraud_model,
    precision_at_alert_rate,
    precision_recall_curve,
    recall_at_alert_rate,
    step_up_friction,
    supervised_layer_scope,
)
from .velocity import (
    DEFAULT_ALLOWED_LATENESS,
    WINDOWS,
    ApplicationEvent,
    Dimension,
    VelocityCounter,
    VelocityError,
    VelocityFeatures,
    skew_check,
)

__all__ = [
    "ALERT_BUDGET",
    "ANOMALY_FEATURE",
    "DEFAULT_ALLOWED_LATENESS",
    "DEFAULT_MAX_SAMPLES",
    "DEFAULT_N_ESTIMATORS",
    "EVALUATION_ALERT_RATE",
    "GEOHASH_PRECISION",
    "MATCH_THRESHOLD",
    "MAX_STEP_UP_FRICTION",
    "MINIMUM_CONFIRMED_FRAUDS",
    "WINDOWS",
    "AnomalyError",
    "ApplicationEvent",
    "ApplicationRecord",
    "Dimension",
    "Edge",
    "EdgeType",
    "EntityGraph",
    "EntityResolutionError",
    "FraudEvaluation",
    "FraudLabels",
    "FraudModel",
    "FraudModelError",
    "IsolationForest",
    "MatchScore",
    "Node",
    "NodeType",
    "Scope",
    "VelocityCounter",
    "VelocityError",
    "VelocityFeatures",
    "anomaly_feature",
    "average_path_length",
    "average_precision",
    "build_graph",
    "candidate_pairs",
    "compare",
    "evaluate",
    "fit_fraud_model",
    "fit_isolation_forest",
    "geohash",
    "jaro",
    "jaro_winkler",
    "normalise_account",
    "normalise_name",
    "normalise_phone",
    "precision_at_alert_rate",
    "precision_recall_curve",
    "recall_at_alert_rate",
    "resolve",
    "skew_check",
    "step_up_friction",
    "supervised_layer_scope",
]
