"""Credit scoring — target engineering, scorecard, challenger, validation.

Phase 1 WS-1.1 (SRS §4). Track A reference implementations behind the same
interfaces the Track B stack (OptBinning, LightGBM, scikit-learn, SHAP, Fairlearn)
plugs into — see ADR-0003 and each module's ``ports`` note.

Workstream: WS-1.1
"""

from .binning import Bin, Binning, BinningError, fit_binning, information_value
from .gbm import (
    DECREASING,
    INCREASING,
    UNCONSTRAINED,
    GBM,
    GBMError,
    MonotoneConstraints,
    Node,
    fit_gbm,
)
from .features import (
    IV_CEILING,
    IV_FLOOR,
    PROTECTED_ATTRIBUTES,
    PSI_ACT,
    PSI_ALERT,
    FeatureCatalogue,
    FeatureError,
    FeatureGroup,
    NullPolicy,
    PointInTimeRule,
    ProtectedAttribute,
    ProtectedAttributeAccess,
    ProtectedAttributeLeak,
    ScoringFeature,
    ScreenVerdict,
    application_scorecard_catalogue,
    psi,
    screen_iv,
    screen_psi,
)
from .isotonic import (
    Direction,
    IsotonicCalibrator,
    fit_isotonic,
    fit_values,
    pool_adjacent_violators,
)
from .scorecard import (
    PDO,
    SCORE_ANCHOR,
    Characteristic,
    Reason,
    ScaleAnchor,
    Scorecard,
    ScorecardError,
    fit_scorecard,
    negative_coefficients,
)
from .splits import (
    MINIMUM_BADS_FOR_CHALLENGER,
    Part,
    RandomSplitForbidden,
    SplitError,
    SplitManifest,
    Splits,
    holdout_without_time_axis,
    manifest,
    split_by_vintage,
)
from .target import (
    PHASE_1_EXCLUSIONS,
    Application,
    Exclusion,
    LabelProvenance,
    TargetError,
    TargetLedger,
    TargetRow,
    TargetTable,
    UnenforceableExclusion,
    build_target_table,
)

__all__ = [
    "DECREASING",
    "GBM",
    "GBMError",
    "INCREASING",
    "IV_CEILING",
    "PDO",
    "IV_FLOOR",
    "MINIMUM_BADS_FOR_CHALLENGER",
    "PROTECTED_ATTRIBUTES",
    "PSI_ACT",
    "PSI_ALERT",
    "SCORE_ANCHOR",
    "UNCONSTRAINED",
    "PHASE_1_EXCLUSIONS",
    "Application",
    "Bin",
    "Binning",
    "BinningError",
    "Characteristic",
    "Direction",
    "Exclusion",
    "FeatureCatalogue",
    "FeatureError",
    "FeatureGroup",
    "IsotonicCalibrator",
    "MonotoneConstraints",
    "Node",
    "LabelProvenance",
    "NullPolicy",
    "PointInTimeRule",
    "ProtectedAttribute",
    "ProtectedAttributeAccess",
    "ProtectedAttributeLeak",
    "Part",
    "RandomSplitForbidden",
    "SplitError",
    "SplitManifest",
    "Reason",
    "ScaleAnchor",
    "Scorecard",
    "ScorecardError",
    "ScoringFeature",
    "ScreenVerdict",
    "Splits",
    "TargetError",
    "TargetLedger",
    "TargetRow",
    "TargetTable",
    "UnenforceableExclusion",
    "application_scorecard_catalogue",
    "build_target_table",
    "fit_binning",
    "fit_gbm",
    "fit_isotonic",
    "fit_scorecard",
    "fit_values",
    "holdout_without_time_axis",
    "information_value",
    "manifest",
    "negative_coefficients",
    "pool_adjacent_violators",
    "psi",
    "screen_iv",
    "screen_psi",
    "split_by_vintage",
]
