"use client";

/**
 * SRS Module 5 — default prediction (PD / LGD / EAD), as its own screen.
 *
 * Unlike the agri and fraud module pages, this one fetches nothing. Every other
 * screen renders a decision about one customer; this module produces
 * *portfolio-level* parameters, and there is no per-application view of a
 * lifetime PD term structure that means anything to a reviewer.
 *
 * So this screen states what the module computes, what it was measured on, and
 * where the numbers came from — with each figure carrying the track that
 * produced it, which is the discipline the whole repository runs on.
 *
 * WHY THESE NUMBERS ARE NOT GATE EVIDENCE, SAID ON THE SCREEN
 * ------------------------------------------------------------
 * The figures below are real: a 19-year US mortgage panel, 16.8 million rows
 * read, 338,210 account-months after construction. They are also Track P, which
 * means they are facts about US mortgages and not about any Indian lender's
 * book. A c-index of 0.6967 on Fannie Mae says the code survives real data with
 * real missingness and real censoring. It says nothing about this bank, and a
 * screen that showed it without that caveat would be the exact failure the
 * three-track model exists to prevent.
 */

import { AppShell } from "../../../components/shell/AppShell";

interface Measured {
  readonly model: string;
  readonly metric: string;
  readonly value: string;
  readonly basis: string;
}

/**
 * Read from `reports/trackP_p3_fannie_mae.json`, which is regenerated by
 * `make trackp-p3`. Transcribed rather than fetched because this is a static
 * description of a committed run, not live portfolio state — and a screen that
 * fetched it would imply these update, which they do not.
 */
const MEASURED: readonly Measured[] = [
  {
    model: "Cox proportional hazards",
    metric: "c-index",
    value: "0.6967",
    basis: "338,210 account-months",
  },
  {
    model: "Discrete-time hazard",
    metric: "AUC",
    value: "0.6127",
    basis: "87,810 held-out rows",
  },
  {
    model: "Survival calibration",
    metric: "Integrated Brier",
    value: "0.0902",
    basis: "lower is better",
  },
];

interface Component {
  readonly name: string;
  readonly what: string;
  readonly state: string;
  readonly blocked: string | null;
}

const COMPONENTS: readonly Component[] = [
  {
    name: "PD — probability of default",
    what: "Discrete-time hazard and Cox models over a monthly account panel, producing a lifetime term structure rather than a point estimate.",
    state:
      "Built, tested, and fitted on a real 19-year panel. Month-on-book enters as an ordered numeric feature rather than dummies — a deliberate deviation, because dummies discard the ordering a tree needs.",
    blocked: null,
  },
  {
    name: "LGD — loss given default",
    what: "Two-stage: a cure model, then a loss-severity model conditional on not curing.",
    state:
      "Built. The first stage needs a cure definition, which Appendix A defines default but not cure. The loss basis — whether credit enhancement is netted off — flips the sign of the LTV coefficient on real data.",
    blocked: "LH-309 · LH-311",
  },
  {
    name: "EAD — exposure at default",
    what: "Credit-conversion factors on undrawn commitments.",
    state:
      "Structurally not measurable here, and that is different from unmeasured: there is no revolving product on any track, so the denominator is identically zero. No effort inside this repository changes that.",
    blocked: "LH-303",
  },
  {
    name: "IFRS 9 staging",
    what: "Significant-increase-in-credit-risk transfer logic across the three stages.",
    state:
      "Built. The SICR thresholds and the origination lifetime PD they are relative to are both unratified — and staging drives provisioning, so a guessed threshold moves a reported number.",
    blocked: "LH-301 · LH-308",
  },
];

export default function RiskModulePage() {
  return (
    <AppShell
      active="/modules/risk"
      title="Default prediction"
      subtitleKey="modules.risk.subtitle"
    >
      <section aria-labelledby="measured-heading">
        <h2
          id="measured-heading"
          className="text-xs font-semibold uppercase tracking-wide text-neutral-700"
        >
          Measured on real data
        </h2>
        <p className="mt-2 max-w-2xl text-sm text-neutral-600">
          The full pipeline ran end to end against a 19-year mortgage panel:
          16,782,203 performance rows read, 338,210 account-months constructed,
          827 default events observed.
        </p>

        <ul className="mt-4 grid gap-3 sm:grid-cols-3">
          {MEASURED.map((m) => (
            <li key={m.model} className="rounded border border-neutral-300 bg-white p-4">
              <p className="font-mono text-2xl font-semibold tabular-nums text-brand-800">
                {m.value}
              </p>
              <p className="mt-1 text-sm font-semibold text-neutral-900">{m.model}</p>
              <p className="mt-0.5 text-xs text-neutral-600">
                {m.metric} · {m.basis}
              </p>
            </li>
          ))}
        </ul>

        <p
          role="note"
          className="mt-4 rounded border border-dashed border-tier-amber bg-amber-50 p-4 text-xs text-neutral-800"
        >
          <strong>These are Track P numbers.</strong> Real loans, real
          missingness, real censoring — and a US mortgage book, not an Indian
          lender&apos;s. A c-index of 0.6967 on Fannie Mae proves the code
          survives real data. It is evidence about the implementation, and it is
          not gate evidence for any bank.
        </p>
      </section>

      <section aria-labelledby="components-heading" className="mt-8">
        <h2
          id="components-heading"
          className="text-xs font-semibold uppercase tracking-wide text-neutral-700"
        >
          The four parameters, and what each still needs
        </h2>

        <ul className="mt-4 flex flex-col gap-3">
          {COMPONENTS.map((c) => (
            <li key={c.name} className="rounded border border-neutral-300 bg-white p-4">
              <div className="flex flex-wrap items-baseline gap-x-3">
                <span className="text-sm font-semibold text-neutral-900">{c.name}</span>
                {c.blocked !== null ? (
                  <span className="ml-auto rounded bg-amber-50 px-2 py-0.5 font-mono text-xs text-tier-amber">
                    {c.blocked}
                  </span>
                ) : (
                  <span className="ml-auto rounded bg-emerald-50 px-2 py-0.5 font-mono text-xs text-fresh-ok">
                    measured
                  </span>
                )}
              </div>
              <p className="mt-1 text-xs text-neutral-600">{c.what}</p>
              <p className="mt-2 text-xs leading-relaxed text-neutral-700">{c.state}</p>
            </li>
          ))}
        </ul>
      </section>
    </AppShell>
  );
}
